### ISSUE TITLE
Configure  Recordings Directory not possible

### ISSUE THREAD

**Issue by krambriw** [bjm904/node-red-contrib-timelapse-from-recordings#1]
Hi, I am not able to configure the directory. If I try "/home/pi/Videos" it is not saved

**Comment by krambriw** [comment]
Need to add; I run Node-RED on a Raspberry Pi 3B+ and this is the error message I get:
"TypeError: The "path" argument must be of type string. Received undefined"

Is this node supposed to only run with Node-RED on specific platforms? Like Windows or so

**Comment by krambriw** [comment]
Sorry closed by mistake

**Comment by krambriw** [comment]
Sorry closed by mistake

Need to add; I run Node-RED on a Raspberry Pi 3B+ and this is the error message I get:
"TypeError: The "path" argument must be of type string. Received undefined"

Is this node supposed to only run with Node-RED on specific platforms? Like Windows or so

**Comment by bjm904** [comment]
Hello, I apologize for the confusion. This project is still work in progress at the moment but will be in working order in a few days. Please check back then. I have updated the README
